runtime: php
env: flex

runtime_config:
  document_root: .

handlers:
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301
  static_files:
    - index.php
    - style.css
  upload: .(php|css)$
